### ISSUE TITLE
Incorrect generated code for the PerBlock lifetime: a local or parameter named ... cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter

### ISSUE THREAD

**Issue by YoshihiroIto** [DevTeam/Pure.DI#140]
Hi,

After upgrading Pure.DI from `v2.3.3` to `v2.3.4`, our project stopped building without source changes other than the
package update.

The same codebase builds successfully with `v2.3.3`, but fails with `v2.3.4`, so this looks like a backward
compatibility regression in generated code.

## Environment

- Pure.DI: `2.3.3` -> `2.3.4`
- .NET: `10.0.4`
- OS: Windows 10 x64

## Actual behavior

`v2.3.4` generates code that does not compile.

Example error:

```txt
error CS0136: A local or parameter named 'perBlockFunc72d279' cannot be declared in this scope because that name is
used in an enclosing local scope to define a local or parameter

The error is reported from generated code under:

obj\Release\net10.0\Pure.DI\Pure.DI.SourceGenerator\...\Composition.g.cs
```

## Expected behavior

A project that builds with v2.3.3 should continue to build with v2.3.4, or any incompatibility should be documented
clearly.

## Observed patterns

The regression seems related to previously working registration patterns such as:

```
.Bind<AppConfig>().To(ctx =>
{
    ctx.Inject<ILoggerService>(out var logger);
    ctx.Inject<IConfigService>(out var configService);
    return new AppConfig(..., logger, configService);
})
```
and also to generated factories such as:

```
Func<IFileSystem, PDFService>
```

used in multiple places in the object graph.

From inspection of the generated code, it appears that v2.3.4 may generate duplicate local names in the same enclosing
scope, which then causes CS0136.

## Why I believe this is a compatibility issue

These patterns worked with v2.3.3 and required no source changes before the package upgrade.

We were able to work around the issue by refactoring some registrations and avoiding part of the generated factory
path, but that required source changes in a project that previously built successfully on v2.3.3.

**Comment by NikolayPianikov** [comment]
@YoshihiroIto сould you share the DI setup? Unfortunately, I can't reproduce this issue.

**Comment by NikolayPianikov** [comment]
@YoshihiroIto thank you!

**Comment by YoshihiroIto** [comment]
@NikolayPianikov 
I've confirmed the fix in the latest version. Thank you for your time and effort.
