### ISSUE TITLE
Build fails after upgrading Pure.DI from 2.2.15 to 2.3.0

### ISSUE THREAD

**Issue by YoshihiroIto** [DevTeam/Pure.DI#128]
I updated Pure.DI from 2.2.15 to 2.3.0, but my local project build is now failing.

Since I cannot find the release notes or changelog for 2.3.0, I am not sure how to address these errors. Any guidance or advice on how to fix this would be greatly appreciated.

**Comment by NikolayPianikov** [comment]
@YoshihiroIto sorry, I posted the release notes late. There are indeed some incompatible changes, related to constructors. Details are [here](https://github.com/DevTeam/Pure.DI/releases/tag/2.3.0).

If you need help, please submit a details like compilation errors. And if possible, please include the code snippet showing the compilation issue. It may take some time to resolve this issue. So, for now, you can roll back to the previous version. Sorry for the inconvenience.
